language: node_js
sudo: false
node_js:
- '8'
addons:
  apt:
    packages:
    - sshpass
deploy:
  provider: heroku
  api_key:
    secure: "$key"
  app: broforce-frontend
  on:
    repo: frontend-park-mail-ru/2018_1_BroForce
    branch: develop
  skip_cleanup: true
script:
- npm run eslint
after_success:
- chmod +x ./deploy.sh; ./deploy.sh;
before_install:
- openssl aes-256-cbc -K $encrypted_32fcade0a95b_key -iv $encrypted_32fcade0a95b_iv
  -in deploy_key.enc -out deploy_key -d
